#!/bin/bash

. ../env/general.conf

set -e

checkAndCreateDir "${WALLETS_PATH}"

cd "${WALLETS_PATH}" || exit 1

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_1}"

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_1}"/"${DIGITALIS_BOARD_MEMBER_1_FIRST_WALLET}"
checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_1}"/"${DIGITALIS_BOARD_MEMBER_1_SECOND_WALLET}"
checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_1}"/"${DIGITALIS_BOARD_MEMBER_1_THIRD_WALLET}"

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_2}"

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_2}"/"${DIGITALIS_BOARD_MEMBER_2_FIRST_WALLET}"
checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_2}"/"${DIGITALIS_BOARD_MEMBER_2_SECOND_WALLET}"
checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_2}"/"${DIGITALIS_BOARD_MEMBER_2_THIRD_WALLET}"

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_3}"

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_3}"/"${DIGITALIS_BOARD_MEMBER_3_FIRST_WALLET}"
checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_3}"/"${DIGITALIS_BOARD_MEMBER_3_SECOND_WALLET}"
checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_3}"/"${DIGITALIS_BOARD_MEMBER_3_THIRD_WALLET}"

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_4}"

checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_4}"/"${DIGITALIS_BOARD_MEMBER_4_FIRST_WALLET}"
checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_4}"/"${DIGITALIS_BOARD_MEMBER_4_SECOND_WALLET}"
checkAndCreateDir "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_4}"/"${DIGITALIS_BOARD_MEMBER_4_THIRD_WALLET}"

checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"

checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_1}"

checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_1}"/"${CORE_TEAM_MEMBER_1_FIRST_WALLET}"
checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_1}"/"${CORE_TEAM_MEMBER_1_SECOND_WALLET}"
checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_1}"/"${CORE_TEAM_MEMBER_1_THIRD_WALLET}"

checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_2}"

checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_2}"/"${CORE_TEAM_MEMBER_2_FIRST_WALLET}"
checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_2}"/"${CORE_TEAM_MEMBER_2_SECOND_WALLET}"
checkAndCreateDir "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_2}"/"${CORE_TEAM_MEMBER_2_THIRD_WALLET}"

checkAndCreateDir "${TREASURY_SECTOR}"
checkAndCreateDir "${TREASURY_SECTOR}"/"${TREASURER}"
checkAndCreateDir "${TREASURY_SECTOR}"/"${TREASURY_BOARD_MEMBER_1}"
checkAndCreateDir "${TREASURY_SECTOR}"/"${TREASURY_BOARD_MEMBER_2}"
checkAndCreateDir "${TREASURY_SECTOR}"/"${TREASURY_BOARD_MEMBER_3}"

checkAndCreateDir "${GOVERNANCE_SECTOR}"
checkAndCreateDir "${GOVERNANCE_SECTOR}"/"${GOVERNANCE_ADMIN_1}"
checkAndCreateDir "${GOVERNANCE_SECTOR}"/"${GOVERNANCE_ADMIN_2}"

checkAndCreateDir "${DNS_SECTOR}"
checkAndCreateDir "${DNS_SECTOR}"/"${DNS_ADMIN_1}"
checkAndCreateDir "${DNS_SECTOR}"/"${DNS_ADMIN_2}"

checkAndCreateDir "${MARKETPLACE_SECTOR}"
checkAndCreateDir "${MARKETPLACE_SECTOR}"/"${MARKETPLACE_ADMIN_1}"
checkAndCreateDir "${MARKETPLACE_SECTOR}"/"${MARKETPLACE_ADMIN_2}"

checkAndCreateDir "${USERS_PATH}"
checkAndCreateDir "${USERS_PATH}"/"${USER_1}"
checkAndCreateDir "${USERS_PATH}"/"${USER_2}"
checkAndCreateDir "${USERS_PATH}"/"${USER_3}"
checkAndCreateDir "${USERS_PATH}"/"${USER_4}"
checkAndCreateDir "${USERS_PATH}"/"${USER_5}"
checkAndCreateDir "${USERS_PATH}"/"${USER_6}"
checkAndCreateDir "${USERS_PATH}"/"${USER_7}"

checkAndCreateDir ./"${DIGITALIS_WALLET}"
checkAndCreateDir ./"${COLLATERAL}"
checkAndCreateDir ./"${DEBUGGER}"

cd "${CORE_TEAM_MEMBERS_WALLETS}"/"${CORE_TEAM_MEMBER_1}" || exit 1

checkAndCreateWallet "${CORE_TEAM_MEMBER_1_FIRST_WALLET}"
checkAndCreateWallet "${CORE_TEAM_MEMBER_1_SECOND_WALLET}"
checkAndCreateWallet "${CORE_TEAM_MEMBER_1_THIRD_WALLET}"

cd ..

cd "${CORE_TEAM_MEMBER_2}" || exit 1

checkAndCreateWallet "${CORE_TEAM_MEMBER_2_FIRST_WALLET}"
checkAndCreateWallet "${CORE_TEAM_MEMBER_2_SECOND_WALLET}"
checkAndCreateWallet "${CORE_TEAM_MEMBER_2_THIRD_WALLET}"

cd ../..

cd "${DIGITALIS_BOARD_MEMBERS_WALLETS}"/"${DIGITALIS_BOARD_MEMBER_1}" || exit 1

checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_1_FIRST_WALLET}"
checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_1_SECOND_WALLET}"
checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_1_THIRD_WALLET}"

cd ..

cd "${DIGITALIS_BOARD_MEMBER_2}" || exit 1

checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_2_FIRST_WALLET}"
checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_2_SECOND_WALLET}"
checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_2_THIRD_WALLET}"

cd ..

cd "${DIGITALIS_BOARD_MEMBER_3}" || exit 1

checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_3_FIRST_WALLET}"
checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_3_SECOND_WALLET}"
checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_3_THIRD_WALLET}"

cd ..

cd "${DIGITALIS_BOARD_MEMBER_4}" || exit 1

checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_4_FIRST_WALLET}"
checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_4_SECOND_WALLET}"
checkAndCreateWallet "${DIGITALIS_BOARD_MEMBER_4_THIRD_WALLET}"

cd ../..

cd "${TREASURY_SECTOR}" || exit 1

checkAndCreateWallet "${TREASURER}"
checkAndCreateWallet "${TREASURY_BOARD_MEMBER_1}"
checkAndCreateWallet "${TREASURY_BOARD_MEMBER_2}"
checkAndCreateWallet "${TREASURY_BOARD_MEMBER_3}"

cd ..

cd "${GOVERNANCE_SECTOR}" || exit 1

checkAndCreateWallet "${GOVERNANCE_ADMIN_1}"
checkAndCreateWallet "${GOVERNANCE_ADMIN_2}"

cd ..

cd "${DNS_SECTOR}" || exit 1

checkAndCreateWallet "${DNS_ADMIN_1}"
checkAndCreateWallet "${DNS_ADMIN_2}"

cd ..

cd "${MARKETPLACE_SECTOR}" || exit 1

checkAndCreateWallet "${MARKETPLACE_ADMIN_1}"
checkAndCreateWallet "${MARKETPLACE_ADMIN_2}"

cd ..

cd "${USERS_PATH}" || exit 1

checkAndCreateWallet "${USER_1}"
checkAndCreateWallet "${USER_2}"
checkAndCreateWallet "${USER_3}"
checkAndCreateWallet "${USER_4}"
checkAndCreateWallet "${USER_5}"
checkAndCreateWallet "${USER_6}"
checkAndCreateWallet "${USER_7}"

cd ..

checkAndCreateWallet ./"${DIGITALIS_WALLET}"
checkAndCreateWallet ./"${COLLATERAL}"
checkAndCreateWallet ./"${DEBUGGER}"
